version: "3"
services:
    github-pages:
        image: starefossen/github-pages
        command: jekyll serve -d /_site --watch --force_polling --livereload --verbose -H 0.0.0.0 -P 4000
        ports:
            - 4000:4000
            - 35729:35729
        volumes:
            - $PWD:/usr/src/app/

        
        
